modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="all_the_blocks_for_everything"
version="1.0.0"
displayName="All the blocks for everything"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ModdyCraft, MCreator"
description='''
Now with most of the blocks that we have in this wonderful game we are going to be able to make stairs buttons some more things, you will be able to discover them on your own. This mod is in alpha phase.
'''

[[dependencies.all_the_blocks_for_everything]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




